name: Release

on:
  push:
    tags: ['v*.*.*']

jobs:
  build-mod:
    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: microsoft/setup-msbuild@v2
  
    # From https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - run: vcpkg integrate install
      working-directory: archipelago-client
    - name: Build mod
      run: msbuild archipelago-client\archipelago-client.vcxproj -verbosity:diag '-property:Configuration=Release;Platform=x64'
      
    - uses: actions/upload-artifact@v4
      with:
        name: archipelago.dll
        path: archipelago-client\x64\Release\archipelago.dll

  build-static:
    runs-on: windows-latest  
    steps:
    - uses: actions/checkout@v4
      with:
        repository: nex3/SoulsRandomizers
        ref: archipelago-server
        path: SoulsRandomizers
    - uses: actions/checkout@v4
      with:
        repository: thefifthmatt/SoulsIds
        # Later versions expect AC6 stuff from SoulsFormats which hasn't been published yet.
        ref: 986346a705799f528d620c19ca384e21cb008b54
        path: SoulsIds
    - uses: actions/checkout@v4
      with:
        repository: thefifthmatt/SoulsFormats
        ref: dsms
        path: SoulsFormats
    - uses: microsoft/setup-msbuild@v2
  
    - name: Install dependencies
      run: dotnet restore SoulsRandomizers\SoulsRandomizers.sln

    - name: Build randomizer
      run: msbuild SoulsRandomizers\DS3Randomizer\DS3Randomizer.csproj '-property:Configuration=Release (Archipelago);PublishDir=bin\publish;PublishProtocol=FileSystem;_TargetId=Folder' '-t:Build;Publish'
      
    - uses: actions/upload-artifact@v4
      with:
        name: DS3Randomizer.exe
        path: SoulsRandomizers\DS3Randomizer\bin\publish\DS3Randomizer.exe
